# Generated by Django 3.0.3 on 2020-06-08 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200608_1851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='current_user',
            new_name='current_user_profile',
        ),
        migrations.RenameField(
            model_name='friend',
            old_name='users',
            new_name='friends',
        ),
    ]
