# Generated by Django 3.0.3 on 2020-06-22 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200610_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='pending_friends',
            field=models.ManyToManyField(default=None, related_name='pending_friends', to='accounts.Profile'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='friends',
            field=models.ManyToManyField(default=None, related_name='friends', to='accounts.Profile'),
        ),
    ]
