# Generated by Django 3.0.3 on 2020-06-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200622_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='my_pending_friends',
            field=models.ManyToManyField(default=None, related_name='my_pending_friends', to='accounts.Profile'),
        ),
    ]
