# Generated by Django 3.0.3 on 2020-06-10 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='icon',
            field=models.ImageField(default='default.jpg', null=True, upload_to='forum_icons'),
        ),
    ]
