# Generated by Django 3.0.3 on 2020-06-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0002_forum_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='title',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
