# Generated by Django 3.0.3 on 2020-06-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0004_auto_20200612_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='default title', max_length=100),
        ),
        migrations.AlterField(
            model_name='forum',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='subforum',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='subforum',
            constraint=models.UniqueConstraint(fields=('forum', 'title'), name='unique forum title'),
        ),
    ]
