# Generated by Django 3.0.3 on 2020-06-12 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0005_auto_20200612_1601'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subforum',
            name='unique forum title',
        ),
        migrations.AlterField(
            model_name='subforum',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterUniqueTogether(
            name='subforum',
            unique_together={('forum', 'slug')},
        ),
    ]
