# Generated by Django 3.0.3 on 2020-06-17 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0006_auto_20200612_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together={('subForum', 'slug')},
        ),
    ]
