# Generated by Django 3.0.3 on 2020-06-18 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0007_auto_20200617_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='slug',
        ),
    ]
