# Generated by Django 3.0.3 on 2020-06-19 00:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('explore', '0009_auto_20200618_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='down',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='up',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='down',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='up',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='comment',
            name='downvote',
        ),
        migrations.AddField(
            model_name='comment',
            name='downvote',
            field=models.ManyToManyField(blank=True, related_name='comment_downvote', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='comment',
            name='upvote',
        ),
        migrations.AddField(
            model_name='comment',
            name='upvote',
            field=models.ManyToManyField(blank=True, related_name='comment_upvote', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='post',
            name='downvote',
        ),
        migrations.AddField(
            model_name='post',
            name='downvote',
            field=models.ManyToManyField(blank=True, related_name='post_downvote', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='post',
            name='upvote',
        ),
        migrations.AddField(
            model_name='post',
            name='upvote',
            field=models.ManyToManyField(blank=True, related_name='post_upvote', to=settings.AUTH_USER_MODEL),
        ),
    ]
