# Generated by Django 3.0.3 on 2020-06-19 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0010_auto_20200619_0021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='down',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='up',
        ),
        migrations.RemoveField(
            model_name='post',
            name='down',
        ),
        migrations.RemoveField(
            model_name='post',
            name='up',
        ),
    ]
