# Generated by Django 3.0.3 on 2020-06-22 15:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('explore', '0011_auto_20200619_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='downvote',
            field=models.ManyToManyField(blank=True, default=None, related_name='post_downvote', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='upvote',
            field=models.ManyToManyField(blank=True, default=None, related_name='post_upvote', to=settings.AUTH_USER_MODEL),
        ),
    ]
