# Generated by Django 3.0.3 on 2020-08-31 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0012_auto_20200622_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='icon',
            field=models.ImageField(null=True, upload_to='forum_icons/'),
        ),
    ]
