# Generated by Django 3.0.3 on 2020-09-09 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0013_auto_20200831_1610'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subforum',
            unique_together={('forum',), ('slug',)},
        ),
    ]
