# Generated by Django 3.0.3 on 2020-09-09 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0014_auto_20200909_2204'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subforum',
            unique_together={('slug', 'forum')},
        ),
    ]
