# Generated by Django 3.0.3 on 2020-09-09 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0015_auto_20200909_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subforum',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
